<div id="create-product-modal" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Product</h5>
            </div>

            <div id="create-product-alert" class="alert alert-warning" role="alert" style="display: none;"></div>

            <div class="modal-body">
                <div class="form-group col-sm-6">
                    <label for="create-product-price">Name</label>
                    <input type="text" name="create-product-name" id="create-product-name" class="form-control" min="0">
                </div>

                <div class="form-group col-sm-6">
                    <label for="create-product-price">Price</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">$</div>
                        </div>
                        <input type="number" name="create-product-price" id="create-product-price" class="form-control" min="0">
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label for="create-product-price">Description</label>
                    <input type="text" name="create-product-description" id="create-product-description" class="form-control" min="0">
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" id="create-product" class="btn btn-primary">Create</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>