<div class="form-row mt-4 mb-2">
    <div class="col-auto">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Products per page</div>
            </div>
            <select name="limit" id="product-table-limit" class="form-control">
                <option value="10">10</option>
                <option value="25" selected>25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Page</div>
            </div>
            <input type="number" name="page" id="product-table-page" class="form-control" value="1" min="1">
        </div>
    </div>
    <div class="col-auto">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Sort</div>
            </div>
            <select name="sort" id="product-table-sort" class="form-control">
                <option value="id">ID</option>
                <option value="name">Name</option>
                <option value="description">Description</option>
                <option value="price">Price</option>
            </select>
        </div>
    </div>
    <div id="product-table-sort-direction" class="col-auto btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-light active">
            <input type="radio" name="asc" autocomplete="off" value="" checked>ASC
        </label>
        <label class="btn btn-light">
            <input type="radio" name="desc" autocomplete="off" value='-'>DESC
        </label>
    </div>
    <div class="col-auto">
        <button id="product-table-filter" class="btn btn-primary">Filter</button>
    </div>
</div>

<div id="product-table-alert" class="alert alert-warning" role="alert" style="display: none;"></div>

<div class="row">
    <div class="col-xs-12 table-responsive">
        <table id="product-table" class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>
                        Action <a href="#" data-toggle="modal" data-target="#create-product-modal"><i class="fas fa-plus-circle fa-fw" ></i></a>
                    </th>
                </tr>
            </thead>
            <tbody id="product-table-body">
                <?php if (empty($products)) : ?>
                    <tr><td colspan="4" class="text-center">No products</td></tr>
                <?php endif; ?>

                <?php foreach ($products as $product) : ?>
                    <tr data-product-id="<?= $product['id'] ?>">
                        <td><?= $product['id'] ?></td>
                        <td class="product-name"><?= $product['name'] ? $product['name'] : '-' ?></td>
                        <td class="product-description"><?= $product['description'] ? $product['description'] : '-' ?></td>
                        <td class="product-price-col">
                            <?php if ($product['price']) : ?>
                                $<span class="product-price"><?= number_format($product['price'], 2) ?></span>
                            <?php else : ?>
                                -
                            <?php endif; ?>
                        </td>
                        <td class="product-actions">
                            <a href="#"><i class="fas fa-pencil-alt fa-fw edit-product"></i></a>
                            <a href="#"><i class="fas fa-trash fa-fw delete-product"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <p class="text-light">
            Showing <span id="product-table-pagination"><?= '1-' . count($products) ?></span> of <span id="product-table-total"><?= $total ?></span> products
        </p>
    </div>
</div>

<?= $this->partial('create-product.phtml') ?>