<div class="form-row mt-4 mb-2">
    <div class="col-auto">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Products per page</div>
            </div>
            <select name="limit" id="product-table-limit" class="form-control">
                <option value="10">10</option>
                <option value="25" selected>25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <option value="">All</option>
            </select>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Page</div>
            </div>
            <input type="number" name="page" id="product-table-page" class="form-control" value="1" min="1">
        </div>
    </div>
    <div class="col-auto">
        <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">Sort</div>
            </div>
            <select name="sort" id="product-table-sort" class="form-control">
                <option value="id">ID</option>
                <option value="name">Name</option>
                <option value="description">Description</option>
                <option value="price">Price</option>
            </select>
        </div>
    </div>
    <div class="col-auto btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-light active">
            <input type="radio" name="options" id="option1" autocomplete="off" checked>ASC
        </label>
        <label class="btn btn-light">
            <input type="radio" name="options" id="option2" autocomplete="off">DESC
        </label>
    </div>
    <div class="col-auto">
        <button class="btn btn-primary">Filter</button>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 table-responsive">
        <table id="product-table" class="table table-striped table-dark">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($products)) : ?>
                    <tr><td colspan="4" class="text-center">No products</td></tr>
                <?php endif; ?>

                <?php foreach ($products as $product) : ?>
                    <tr>
                        <td><?= $product['id'] ?></td>
                        <td><?= $product['name'] ?></td>
                        <td><?= $product['description'] ?></td>
                        <td><?= $product['price'] ?></td>
                        <td>
                            <a href="#"><i class="fas fa-pencil-alt fa-fw"></i></a>
                            <a href="#"><i class="fas fa-trash fa-fw"></i></a>    
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <p class="text-light">Showing <?= count($products) ?> of <?= count($products) ?> products</p>
    </div>
</div>
